/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regex;

import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class ValidacaoDataCPF extends javax.swing.JFrame {

    /**
     * Creates new form ValidacaoDataCPF
     */
    public ValidacaoDataCPF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        LblCPF = new javax.swing.JLabel();
        LblData1 = new javax.swing.JLabel();
        fieldCPF = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        fieldData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCPF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblCPF.setText("CPF");

        LblData1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblData1.setText("Data");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblData1)
                            .addComponent(LblCPF)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnEnviar))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(LblData1)
                .addGap(18, 18, 18)
                .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(LblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        String strData = fieldData.getText();
        String strCpf = fieldCPF.getText();

        if (strCpf.isEmpty() || strData.isEmpty()) {
            JOptionPane.showMessageDialog(jPanel, "Todos os campos devem ser preenchidos!", "Campos em branco",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String testeData = fieldData.getText();
            boolean dataValida = testeData.matches("[0-9]{2}[/][0-9]{2}/[0-9]{4}");
            String testeCpf = fieldCPF.getText();
            Boolean cpfValido = testeCpf.matches("[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}");

            if (dataValida && cpfValido) {
                JOptionPane.showMessageDialog(null, "você inseriu a data e o cpf nos formatos válidos ");
            } else if (!dataValida && cpfValido) {
                JOptionPane.showMessageDialog(null, "Data precisa ser no formato dd/mm/aaaa ");
            } else if (dataValida && !cpfValido) {
                JOptionPane.showMessageDialog(null, "Cpf precisa se no formato xxx.xxx.xxx-xx ");
            } else {
                JOptionPane.showMessageDialog(null,
                        "Data precisa ser no formato dd/mm/aaaa e Cpf no formato xxx.xxx.xxx-xx ");
            }
        }
    }// GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidacaoDataCPF.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ValidacaoDataCPF().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCPF;
    private javax.swing.JLabel LblData1;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextField fieldCPF;
    private javax.swing.JTextField fieldData;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
